### ISSUE TITLE
Using entry.linkfield.target returns a 1 instead of actual target string

### ISSUE THREAD

**Issue by lenvanessen** [fruitstudios/craft-linkit#14]

**Comment by samhibberd** [comment]
Hey @lenvanessen,

Thanks for the feedback.

Yes as it stands we return boolean for target rather than assuming how you might want to implement this. Would it be useful to have access to any attributes that would be set on a link as an array?

For the generated link we now set both `target="_blank"` and  `rel="noopener noreferrer"` as per [this article](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/).

Thanks,

Sam

**Comment by samhibberd** [comment]
@lenvanessen any thoughts on this, feeling here is leave it as is, unless you have a good use case to change? 

Any thoughts on this:
> Would it be useful to have access to any attributes that would be set on a link as an array?

**Comment by lenvanessen** [comment]
Hi @samhibberd ,

Sorry for the late reply, for now i do inside the a tag:
```{{ linkfied.getTarget() ? '_blank' : '_self' }}```

Would be nice just to be able to do
``` {{ linkfield.getTarget()}} ``` 
and it would figure out by itself if it's supposed to print _blank of _self (or even more options)

**Comment by samhibberd** [comment]
See in [v1.0.6 ](https://github.com/fruitstudios/craft-linkit/releases/tag/v1.0.6)
